#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DEFAULT_LIST="$SCRIPT_DIR/LIST_OF_ENV_VARIABLES_TO_IMPORT"
LIST_FILE="${1:-$DEFAULT_LIST}"
OUT_DIR="$SCRIPT_DIR/generated"
KITTY_OUT="$OUT_DIR/kitty_env.conf"
ITERM_LAUNCHER="$OUT_DIR/iterm2_env_launcher.sh"
ITERM_PROFILE="$OUT_DIR/iterm2_dynamic_profile.json"

mkdir -p "$OUT_DIR"

read_list() {
  grep -vE '^(#|\s*$)' "$LIST_FILE" \
    | sed 's/[[:space:]]//g' \
    | tr -d '\r'
}

vars=()
names=()
while IFS= read -r name; do
  [ -z "$name" ] && continue
  val=${!name-}
  [ -z "$val" ] && continue
  vars+=("$name=$val")
  names+=("$name")
done < <(read_list)

# Generate kitty env snippet
{
  echo "# Generated by env_sync.sh; include this file from your kitty.conf"
  echo "tab_title_template {index}: {title}"
  if [ ${#vars[@]} -gt 0 ]; then
    for kv in "${vars[@]}"; do
      echo "env $kv"
    done
  fi
} > "$KITTY_OUT"

# Generate iTerm2 launcher which exports env vars and sets tab/window title
{
  echo "#!/usr/bin/env bash"
  echo "set -euo pipefail"
  echo "# Generated by env_sync.sh"
  if [ ${#vars[@]} -gt 0 ]; then
    for kv in "${vars[@]}"; do
      name=${kv%%=*}
      value=${kv#*=}
      esc_value=${value//"/\\"}
      printf 'export %s="%s"\n' "$name" "$esc_value"
    done
  fi
  echo "title_parts=()"
  if [ ${#names[@]} -gt 0 ]; then
    printf 'names=(%s)\n' "${names[*]}"
    echo 'for name in "${names[@]}"; do val="${!name}"; if [ -n "$val" ]; then title_parts+=("$name=$val"); fi; done'
  fi
  echo 'TITLE="tab_env: ${title_parts[*]}"'
  echo 'printf "\033]1;%s\007\033]2;%s\007" "$TITLE" "$TITLE" || true'
  echo 'exec "$SHELL" -l'
} > "$ITERM_LAUNCHER"
chmod +x "$ITERM_LAUNCHER"

# Generate iTerm2 Dynamic Profile pointing to launcher
GUID="8a0c1b7a-1c0f-4b5e-b1f7-$(printf %04x $((RANDOM%65536)))"
LAUNCH_CMD="/bin/bash -lc $ITERM_LAUNCHER"
cat > "$ITERM_PROFILE" <<JSON
{
  "Profiles": [
    {
      "Name": "TUI Env Profile",
      "Guid": "$GUID",
      "Command": "$LAUNCH_CMD",
      "Working Directory": "$ROOT_DIR",
      "Badge Text": "TUI-ENV"
    }
  ]
}
JSON

echo "Generated:" >&2
echo "  $KITTY_OUT" >&2
echo "  $ITERM_LAUNCHER" >&2
echo "  $ITERM_PROFILE" >&2
