name: Data PDF Pipeline

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build local Docker toolchain images
        run: |
          make docker_build_all

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          make setup

      - name: Run CI make target (full pipeline + tests)
        env:
          EMACS_IMAGE: vedarogue/emacs:latest
          TEX_IMAGE: vedarogue/tex:latest
          OCR_IMAGE: vedarogue/ocr:latest
          POPPLER_IMAGE: vedarogue/poppler:latest
          HF_DATASET_ID: manojbalaji1/anveshana
        run: |
          make ci

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: verses-pdf
          path: build/verses.pdf

      - name: Upload Roguelike Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: roguelike-yaml
          path: |
            build/roguelike.yaml
            build/roguelike.baseline.yaml
            build/roguelike.improved.yaml
